#!/bin/bash

set -e
dir=$(readlink -f $(dirname $(readlink -f $0)))
name=$(basename $dir)
cd $dir
. ../functions.sh

cat Dockerfile | dockerfile_buildtime_aptproxy > Dockerfile.1
docker build --pull=true --rm -t $REGISTRY/$name -f Dockerfile.1 .
rm Dockerfile.1

